config/routes.rb
WebstoreApp::Application.routes.draw do

  resources :events

  resources :signups

  resources :renewals

  resources :payments 
  
  resources :plans
      

  
  devise_for :users, :controllers => {:registrations => 'registrations'} 
  devise_scope :user do 
    get '/users/current' => "registrations#show", :as => 'current_user'
    resources :users, :only => [:add, :show] 
    root :to => "registrations#show"
  end 
  

  match "powai" => "events#new"
  match "stores" => "branches#index"
  match "/contact", :to => 'pages#contact'
  match "/tnc", :to => 'pages#tnc'
  match "/privacypolicy", :to => 'pages#privacypolicy'
  match "/about", :to => 'pages#about'
  
  get "pages/privacypolicy"
  get "pages/contact"
  get "pages/tnc"
  get "pages/about"
  
  resources :branches
  match "gatewayentry" => "payments#gatewayentry" , :via => :post

end

app/models/signup.rb
class Signup < ActiveRecord::Base
  include ActiveRecord::Transitions
  
  PAYMENT_MODES = {
    :cash   => 1,
    :check  => 2, 
    :card   => 3
  }  
  
  attr_accessor :check_no, :card_no
  attr_accessible :id, :name, :address, :mphone, :lphone, :email, :referrer_member_id, 
    :employee_no, :plan_id, :branch_id, :signup_months, :payment_mode, :membership_no, 
    :application_no, :coupon_no, :coupon_id, :coupon_amt, :paid_amt, :company_id, 
    :info_source_id, :flag_reversed, :reversal_reason_id, :state
  
  belongs_to :user, :foreign_key => 'created_by'
  belongs_to :user, :foreign_key => 'modified_by'
  belongs_to :plan
  belongs_to :branch
  belongs_to :company
  
  
  validates :name, :presence => true, :length => { :minimum => 2, :maximum => 100 }
  validates :address, :presence => true, :length => { :minimum => 2, :maximum => 100 }
  validates :branch_id, :presence => true
  validates :referrer_member_id, :length => { :maximum => 7 }
  validates :employee_no, :length => { :maximum => 10 }
  validates :membership_no, :presence => true, :length => { :is => 11 }  
  validates :paid_amt, :presence => true, :numericality => { :greater_than => 0 }  
# validates :application_no, :presence => true, :uniqueness => true, :length => { :maximum => 10 }
  validates :payment_mode, :presence => true, :numericality => {:greater_than => 0, :less_than => 4 }
  validates :email, :presence => true
  validates :info_source_id, :presence => { :message => " Please select - How did you come to know about us ?" }
  validate :payment_ref_should_not_be_blank
  validate :atleast_one_phone_number_required
  validate :coupon_no_should_not_be_blank
  validate :paid_amt_greater_than_bill_amt
  validate :membership_no_should_be_unique
  validate :company_and_employee_not_blank
  
  validate :referrer_existence_validation
  validate :membership_dup_validation
  validate :paid_amt_only_rupee_allowed
  validate :email_dup_validation
  validate :validate_membership_format

  before_save :set_defaults
  before_create :company_and_employee_uniqness
  #after_create { generateSignupEvent }
  #after_update { generateNMReversalEvent }
    
  state_machine do
    state :New # first one is the initial state before sending  for payement
    state :PendingPay # if sent to payment gateway
    state :Paid # if sent to payment gateway
    state :Executed
    state :Cancel
    
    event :sent do
      transitions :to => :PendingPay, :from => [:New]
    end
    event :execute do
      transitions :to => :Paid, :from => [:PendingPay]
    end
    event :done do
      transitions :to => :Executed, :from => [:Paid] #, :on_transition => :do_migrate
    end
    event :cancel do
      transitions :to => :Cancel, :from => [:New]
    end
  end
  
  def processEvent(event)
    case 
      when event.eql?('sent') then sent
      when event.eql?('execute') then execute
      when event.eql?('done') then done
      when event.eql?('cancel') then cencel
    end
  end

  def coupon_no_should_not_be_blank
      if coupon_no.blank?
        errors.add(:coupon_no, "should not be blank") unless coupon_id.nil?
      end
  end
  
  def payment_ref_should_not_be_blank
    if payment_ref.blank? 
      errors.add(:check_no, "should not be blank") if payment_mode == Signup::PAYMENT_MODES[:check]
      errors.add(:card_no, "should not be blank") if payment_mode == Signup::PAYMENT_MODES[:card]
    end
  end
  
  def atleast_one_phone_number_required
    if mphone.blank? && lphone.blank?
      errors.add(:mphone, "is required")
    end
    unless lphone.blank?
      begin
        errors.add(:lphone, "is more than 10 digits") if lphone.to_s.length > 10
        errors.add(:lphone, "is less than 8 digits") if lphone.to_s.length < 8
      end
    end
    unless mphone.blank?
      begin
        errors.add(:mphone, "should be 10 digits") if mphone.to_s.length != 10
      end
    end
  end

  def paid_amt_greater_than_bill_amt
    unless paid_amt.blank?
      plan = Plan.find(plan_id)
      if (plan.subscription)
        bill_amt = plan.sec_dep + plan.registration_fee+ plan.renewAmount(signup_months)
        errors.add(:paid_amt, "is more than Bill Amount") if paid_amt.to_d > bill_amt.to_d
      else
        bill_amt = plan.ppb_amount(self.signup_months) + plan.registration_fee
        errors.add(:paid_amt, "is more than Bill Amount") if paid_amt.to_d > bill_amt.to_d
      end
    end
  end

  def membership_no_should_be_unique
    signup = Signup.find_by_membership_no_and_flag_reversed(membership_no, 'N')

    unless signup.nil?
      errors.add(:membership_no, "has already been taken") unless id == signup.id
    end
  end

  def company_and_employee_not_blank
      plan = Plan.find(plan_id)

      if employee_no.blank?
        errors.add(:employee_no, "can't be blank for corporate plan!") if plan.plan_type == "C"
      end

      if company_id.blank?
        errors.add(:company_id, "name can't be blank for corporate plan!") if plan.plan_type == "C"
      end
  end

  def company_and_employee_uniqness
        plan = Plan.find(plan_id)
          signup = Signup.find(:all, :conditions=> ["company_id=? and employee_no=? and state in (?)", company_id, employee_no,['Paid', 'Executed']])
           unless signup.blank?
           errors.add(:company_id, " and employee is already a member!") if plan.plan_type == "C"
           return false
           end
  end

  def referrer_existence_validation
   unless referrer_member_id.blank?
      card= Card.find_all_by_membership_no(referrer_member_id)
       if card.blank?
        errors.add(:referrer_member_id, " is not valid!")
       end
  end
 end
 
  def membership_dup_validation
    card= Card.find_all_by_card_id(membership_no)

    unless flag_reversed == 'Y'
      unless card.blank?
        errors.add(:membership_no, " is already in use!")
      end
    end
  end

  def paid_amt_only_rupee_allowed
    if paid_amt != paid_amt.to_i
      errors.add(:paid_amt, " cannot have paise, Please enter Paid Amt in rupees") unless paid_amt.blank?
    end
  end
  
  def email_dup_validation
       

  end 
  
  def validate_membership_format
  
    reg = /^T[[\d]]{10}$/

    if !(reg.match(membership_no))
     errors.add(:base, "Membership number format is wrong, it should be 'T' followed by 6 digits")
    end

  end


  def decode_frequency
      case self.plan.frequency.upcase
      when 'M' then
        'month'
      when 'Y' then
        'year'
      else
      'book per month'
      end
  end

  def migrate
    if self.state.eql?('Paid')
      migrate_signup
      self.done!
      SignupMailer.registration_confirmation(self).deliver
    end
    
  end
  
  def migrate_signup
    
    memp_signup = MempSignup.new
    memp_signup.name = self.name
    memp_signup.address = self.address
    memp_signup.mphone = self.mphone
    memp_signup.lphone = self.lphone
    memp_signup.email = self.email 
    memp_signup.referrer_member_id = self.referrer_member_id
    memp_signup.referrer_cust_id = self.referrer_cust_id
    memp_signup.plan_id = self.plan_id
    memp_signup.branch_id = self.branch_id
    memp_signup.signup_months = self.signup_months
    memp_signup.security_deposit = self.security_deposit
    memp_signup.registration_fee = self.registration_fee
    memp_signup.reading_fee = self.reading_fee
    memp_signup.discount = self.discount
    memp_signup.advance_amt = self.advance_amt
    memp_signup.paid_amt = self.paid_amt
    memp_signup.overdue_amt = self.overdue_amt
    memp_signup.payment_mode = self.payment_mode
    memp_signup.payment_ref = self.payment_ref
    memp_signup.membership_no = self.membership_no
    memp_signup.application_no = self.application_no
    memp_signup.employee_no = self.employee_no
    memp_signup.created_by = 1000
    memp_signup.modified_by = 1000
    memp_signup.flag_migrated = self.flag_migrated
    memp_signup.start_date = self.start_date
    memp_signup.expiry_date = self.expiry_date
    memp_signup.remarks = self.remarks
    memp_signup.created_at = self.created_at
    memp_signup.updated_at = self.updated_at
    memp_signup.coupon_amt = self.coupon_amt
    memp_signup.coupon_no = self.coupon_no
    memp_signup.coupon_id = self.coupon_id
    memp_signup.flag_reversed = self.flag_reversed
    memp_signup.company_id = self.company_id
    memp_signup.info_source_id = self.info_source_id
    memp_signup.reversal_reason_id = self.reversal_reason_id
    memp_signup.created_in = self.branch_id
    memp_signup.modified_in = self.branch_id
    memp_signup.order_id = self.payment_id
    if !memp_signup.save!
      logger.debug'failed to save'
    end
      logger.debug' saved'
  end
  private 
  
  def set_defaults
    plan = Plan.find(plan_id)
    
    self.referrer_cust_id = nil
    self.application_no = '1'
    
    unless self.coupon_id.nil?
      coupon = plan.coupons.find(self.coupon_id)
      self.discount = coupon.discount
      self.coupon_amt = coupon.amount
    else
      self.discount = 0
      self.coupon_amt = 0
      self.coupon_no = nil
    end

    # these values are possibly allowed to be changed during sign-up
    # dont have time to do this
    if plan.subscription
      self.security_deposit = plan.sec_dep
      self.registration_fee = plan.registration_fee
      self.reading_fee = plan.renewAmount(self.signup_months)
    else
      self.security_deposit = plan.ppb_sec_dep(self.signup_months)
      self.registration_fee = plan.registration_fee
      self.reading_fee = plan.ppb_read_fee(self.signup_months)
    end
    self.advance_amt = 0    
    self.overdue_amt = 0

    #part payment starts
    bill_amt = self.security_deposit + self.registration_fee + self.reading_fee - (self.discount + self.coupon_amt)    
    actual_paid_amt = self.paid_amt
    
    if bill_amt > actual_paid_amt
      self.overdue_amt = bill_amt - actual_paid_amt
    end
    #part payment ends    
    
    self.start_date = Time.zone.today
    if plan.subscription

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_filter :authenticate_user!

  # GET /signups
  # GET /signups.xml
  def index
    @signups = Signup.find(:all, :conditions => ['email = ?', current_user.email])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @signups }
    end
  end

  # GET /signups/1
  # GET /signups/1.xml
  def show
    @signup = Signup.find(params[:id])
    if @signup.email.eql?(current_user.email) 
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @signup }
      end
    else
      redirect_to signups_path
    end
  end

  def new
    
    signUpMonths = 1
    @plan = Plan.find(params[:p])
    @branches = @plan.branches.find(:all, :conditions => ['upper(category) IN (?) ',['S','P','W']], :order => ('id'))
    signUpMonths = params[:m].to_i unless params[:m].empty?
    
    if signUpMonths < 1 && @plan.subscription
      redirect_to :plans
    end

    @signup = Signup.new
    @signup.plan_id = @plan.id
    @signup.signup_months = signUpMonths
    @signup.email = current_user.email
    @signup.name = current_user.username
    @signup.branch_id=params[:b]
    if (@plan.subscription)
      @signup.security_deposit = @plan.sec_dep
      @signup.registration_fee = @plan.registration_fee
      @signup.reading_fee = @plan.renewAmount(signUpMonths)
      @signup.paid_amt = @plan.sec_dep + @plan.registration_fee + @plan.renewAmount(signUpMonths)
    else
      @signup.security_deposit = @plan.ppb_sec_dep(signUpMonths)
      @signup.registration_fee = @plan.registration_fee
      @signup.reading_fee = @plan.ppb_read_fee(signUpMonths)
      @signup.paid_amt = @plan.ppb_amount(signUpMonths) + @plan.registration_fee 
    end
    @signup.discount = 0
    @signup.overdue_amt = 0
  end
  
  def create
    
    @signup = Signup.new(params[:signup]) do |q|
      q.created_by = current_user.id
      q.modified_by = current_user.id
      q.membership_no = 'T'+"%010d" % Time.now.to_i
      q.payment_mode = Signup::PAYMENT_MODES[:card]
      # this does not look to be the best way to work with virtual attributes..
      q.payment_ref = 'card'
      q.state = 'New'
    end
    @plan = Plan.find(@signup.plan_id)
    if @signup.save      
      #redirect_to(@signup, :notice => 'Member Signed Up Successfully')
      #SignupMailer.registration_confirmation(@signup).deliver
      redirect_to :action=>"new", :controller=>"payments", :id => @signup.id,:for=>'sig'
    else
      @branches = Branch.find_all_by_category(['S','P','W'], :order=>('id'))
      @branches = @plan.branches.find(:all, :conditions => ['upper(category) IN (?) ',['S','P','W']], :order => ('id'))
      render :action => "new"
    end
        
  end

  
  def compute
    @plan = Plan.find(params[:plan_id])

    render :partial => 'payment', :locals => { :plan => @plan, :signup_months => params[:signup_months].to_i, :coupon_id => params[:coupon_id].to_i }
  end

  def newMemberReversal
    signup_id = params[:signup_id].to_i
    @signup = Signup.find(signup_id)

    if @signup.update_attributes(:flag_reversed => "Y",
        :reversal_reason_id => params[:reversal_reason].to_i,
        :updated_at => Time.zone.today)
      @reportMsg = 'New Member Reversal done for : ' + @signup.membership_no
    else
      @reportMsg = 'New Member Reversal failed for : ' + @signup.membership_no
    end

    render :partial => 'signup_msg'
  end

  def reSendWelcomeMail
    signup = Signup.find(params[:signup_id])
    SignupMailer.registration_confirmation(signup).deliver
    @reportMsg = 'Welcome Mail Re-Sent to - ' + signup.membership_no

    render :partial => 'signup_msg'
  end

  def rePrintReceipt
    @signup = Signup.find(params[:signup_id])

    render :partial => 'reprint_receipt'
  end

  def signups_link
    @sg = Signup.find(params[:signup_id].to_i)
    @card = Card.find_by_membership_no(@sg.membership_no)

    render :partial => 'signup_links'
  end

end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <div class="span-13 border" >   
      <%= f.hidden_field :signup_months, :value=> @signup.signup_months%>
			<%= f.hidden_field :plan_id, :value=> @signup.plan_id%>
      <%= f.hidden_field :email, :value=> @signup.email%>
      <%= f.hidden_field :security_deposit, :value=> @signup.security_deposit%>
      <%= f.hidden_field :registration_fee, :value=> @signup.registration_fee%>
      <%= f.hidden_field :reading_fee, :value=> @signup.reading_fee%>
      <%= f.hidden_field :discount, :value=> @signup.discount%>
      <%= f.hidden_field :paid_amt, :value=> @signup.paid_amt%>
      <%= f.hidden_field :overdue_amt, :value=> @signup.overdue_amt%>
      <%= f.hidden_field :coupon_id %>
      <div class="span-12">
        
        <%= field_set_tag 'Contact Details' do %>
        <span class="span-5">
        <%= f.text_field :name, :maxlength => 30, :style => 'width:100%', :placeholder => 'Name' %></span>
          
          <span class="span-5"><%= f.text_field :email, :readonly=> true, :class => :readonly, :maxlength => 100, :style => 'width:100%' %> </span>
          <span class="span-10">
          <%= f.text_area :address , :maxlength=>1000, :size => "10X5",:placeholder => 'Address' %>
          </span><br/>
          <span class="span-5">
          <%= f.telephone_field :mphone, :maxlength => 10, :style => 'width:100%', :placeholder => 'Phone(M)'%></span>
          <span class="span-5"><%= f.telephone_field :lphone, :maxlength => 10, :style => 'width:100%',:placeholder => 'Phone(L)' %></span>
        <% end -%>
      </div>
      <div class="span-12">
        <%= field_set_tag 'Payment Details' do %>
        <span class="span-5"><%= f.label 'Registration charges ' %> </span><span class="span-5">Rs.
        <%= f.text_field :registration_fee, :readonly => true, :class=>:readonly , :maxlength => 100, :style => 'width:70px;' %></span><br/>
        <span class="span-5"><%= f.label 'Security Deposit (Refundable) ' %> </span><span class="span-5">Rs.
        <%= f.text_field :security_deposit, :readonly => true, :class=>:readonly , :maxlength => 100, :style => 'width:70px;' %></span><br/>
        <span class="span-5"><%= f.label 'Reading Fee ' %></span><span class="span-5">Rs.
        <%= f.text_field :reading_fee, :readonly => true, :class=>:readonly , :maxlength => 100, :style => 'width:70px;' %> </span><br/>
        <span class="span-5"><%= f.label 'Total Amount ' %> </span><span class="span-5" style="color:green;">Rs.
        <b><%= f.text_field :paid_amt, :readonly => true, :class=>:readonlytot , :maxlength => 100, :style => 'width:100px;' %></b></span><br/>
        <% if @plan.plan_type == 'C'%>
          <div class="span-15">
            <%= f.collection_select(:company_id, Company.find(:all, :conditions => ["expiry_date >= ? and start_date <= ?", Date.current, Date.current]), :id, :name, {:include_blank => 'Select Company'} ) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= f.label 'Employee Number *' %>
            <%= f.text_field :employee_no, :maxlength => 10, :style => 'width:100px' %>
          </div>
          <div class="small">*You will be awarded confirmed membership on providing proof of your employment with the company selected </div>
          
        <% end %>
      <% end -%>
      </div>
  </div>
  <div class="span-7"> 
      <%= f.collection_select(:branch_id, @branches, :id, :branch_name, {:include_blank => 'Select Branch'} ) %> <br/>
     
      <%= f.collection_select(:info_source_id, InformationSource.find(:all), :id, :name, {:include_blank => 'How did you come to know about us?'} )%>
      <br/><br/>
      <div class="actions">
        <%= f.submit  "CONTINUE", :class=>"btn_link" %>
        <%= link_to 'Back', :back %>  
      </div>
  </div>
  <div class="span-7">
    <% if @signup.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@signup.errors.count, "error") %> prohibited this signup from being saved:</h4>
      <ul>
      <% @signup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
  </div>

<% end %>

app/views/signups/index.html.erb
<div class="span-25">
<h1>Listing signups</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @signups.each do |signup| %>
  <tr>
    <td><%= link_to 'Show', signup %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Signup', new_signup_path %>
</div>

app/views/signups/new.html.erb
# google analytics tracking code starts
  <%= javascript_tag :defer => 'defer' do -%>
    <script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-24987175-1']);
		  _gaq.push(['_setDomainName', '.justbooksclc.com']);
		  _gaq.push(['_trackPageview']);
		
		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		
		</script>
  <% end %>
# google analytics tracking code ends

<div class="span=25">
<div class="input_box">  
  <div class="breadcrumb"> Signup From : <%= Time.now.strftime('%d-%b-%Y') %> To : <%= (Time.now + @signup.signup_months.months).strftime('%d-%b-%Y') %></div>
  <div class="inner_box">  

    <%= render 'form' %>

  </div>
  
</div>
</div>

app/views/signups/show.html.erb
<div class="span-25">
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_signup_path(@signup) %> |
<%= link_to 'Back', signups_path %>
</div>