config/routes.rb
WebstoreApp::Application.routes.draw do

  resources :events

  resources :signups

  resources :renewals

  resources :payments 
  
  resources :plans
      

  
  devise_for :users, :controllers => {:registrations => 'registrations'} 
  devise_scope :user do 
    get '/users/current' => "registrations#show", :as => 'current_user'
    resources :users, :only => [:add, :show] 
    root :to => "registrations#show"
  end 
  

  match "powai" => "events#new"
  match "stores" => "branches#index"
  match "/contact", :to => 'pages#contact'
  match "/tnc", :to => 'pages#tnc'
  match "/privacypolicy", :to => 'pages#privacypolicy'
  match "/about", :to => 'pages#about'
  
  get "pages/privacypolicy"
  get "pages/contact"
  get "pages/tnc"
  get "pages/about"
  
  resources :branches
  match "gatewayentry" => "payments#gatewayentry" , :via => :post

end

app/models/renewal.rb
class Renewal < ActiveRecord::Base
  include ActiveRecord::Transitions
  belongs_to :member
  belongs_to :payment
  belongs_to :card

  validates :member_id, :presence => true  
  validates :amount, :presence => true
  validates :card_id, :presence => true
  validates :months, :presence => true
  before_create :set_defaults
  state_machine do
    state :New # first one is the initial state before sending  for payement
    state :PendingPay # if sent to payment gateway
    state :Paid # if sent to payment gateway
    state :Executed
    state :Cancel
    
    event :sent do
      transitions :to => :PendingPay, :from => [:New]
    end
    event :execute do
      transitions :to => :Paid, :from => [:PendingPay]
    end
    event :done do
      transitions :to => :Executed, :from => [:Paid]
    end
    event :cancel do
      transitions :to => :Cancel, :from => [:New]
    end
  end
  
  def send_mail
    RenewalMailer.renewal_confirmation(self).deliver
  end
  def processEvent(event)
    case 
      when event.eql?('sent') then sent
      when event.eql?('execute') then execute
      when event.eql?('done') then done
      when event.eql?('cancel') then cencel
    end
  end
  
  def set_defaults
    self.reading_fee = self.member.valid_card[0].renewAmount(self.months)
    self.security_deposit = 0
    self.plan_id = self.member.valid_card[0].plan_id
    self.new_plan_id  = self.member.valid_card[0].plan_id
    if self.member.valid_card[0].auto_changeable?
      self.new_plan_id = self.member.valid_card[0].plan.new_plan_id
    end
  end
end

app/controllers/renewals_controller.rb
class RenewalsController < ApplicationController
  
  before_filter :authenticate_user!

  # GET /renewals/new
  # GET /renewals/new.xml
  def new
    @renewal = Renewal.new
    @renewal.member_id = params[:md]
    mem = Member.find(params[:md])
    months = params[:m]
    @renewal.card_id = mem.valid_card[0].card_id
    @renewal.months = months
    @renewal.amount = mem.valid_card[0].renewAmount(months.to_i)
    @renewal.state = 'New'
    @renewal.from_date = mem.valid_card[0].expiry_date
    @renewal.to_date = mem.valid_card[0].newExpiry(months.to_i)
    @renewal.pay_mode = Signup::PAYMENT_MODES[:card]
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @renewal }
    end
  end

  #def show
  #  @renewal = Renewal.find(params[:id])
  #end
  # POST /renewals
  # POST /renewals.xml
  def create
    @renewal = Renewal.new(params[:renewal])

    if @renewal.save
      redirect_to :action=>"new", :controller=>"payments", :id => @renewal.id,:for=>'ren'
    else
      render :action => "new"
    end
  
  end
end

app/helpers/renewals_helper.rb
module RenewalsHelper
end

app/views/renewals/_form.html.erb
<%= form_for(@renewal) do |f| %>
  <% if @renewal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@renewal.errors.count, "error") %> prohibited this renewal from being saved:</h2>

      <ul>
      <% @renewal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
      Renew Membership: <%= @renewal.card_id %><br/>
      Till : <%= @renewal.to_date.strftime('%d-%b-%Y') %><br/>
      Amount : <%= @renewal.amount %><br/>
      <%= f.hidden_field :card_id , :value=> @renewal.card_id %>
      <%= f.hidden_field :member_id , :value=> @renewal.member_id %>
      <%= f.hidden_field :state , :value=> @renewal.state %>
      <%= f.hidden_field :amount , :value=> @renewal.amount %>
      <%= f.hidden_field :months , :value=> @renewal.months %>
      <%= f.hidden_field :from_date , :value=> @renewal.from_date %>
      <%= f.hidden_field :to_date , :value=> @renewal.to_date %>
      <%= f.hidden_field :pay_mode , :value=> @renewal.pay_mode %>
      <br/>
    <%= f.submit  "CONTINUE", :class=>"btn_link" %>
  </div>
<% end %>

app/views/renewals/edit.html.erb
<div class="span-25">
<h1>Editing renewal</h1>

<%= render 'form' %>

<%= link_to 'Show', @renewal %> |
<%= link_to 'Back', renewals_path %>
</div>

app/views/renewals/index.html.erb
<div class="span-25">
<h1>Listing renewals</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @renewals.each do |renewal| %>
  <tr>
    <td><%= link_to 'Show', renewal %></td>
  </tr>
<% end %>
</table>

<br />

</div>

app/views/renewals/new.html.erb
# google analytics tracking code starts
  <%= javascript_tag :defer => 'defer' do -%>
    <script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-24987175-1']);
		  _gaq.push(['_setDomainName', '.justbooksclc.com']);
		  _gaq.push(['_trackPageview']);
		
		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		
		</script>
  <% end %>
# google analytics tracking code ends

<div class="span-25">
<div class="input_box">  
  <div class="breadcrumb"> RENEW </div>
  <div class="inner_box">  

    <%= render 'form' %>

    <%= link_to 'Back', :back %>
  </div>
</div>
</div>

app/views/renewals/show.html.erb
<div class="span-25">
<p id="notice"><%= notice %></p>


<%= link_to 'Back', :back %>
</div>