config/routes.rb
WebstoreApp::Application.routes.draw do

  resources :events

  resources :signups

  resources :renewals

  resources :payments 
  
  resources :plans
      

  
  devise_for :users, :controllers => {:registrations => 'registrations'} 
  devise_scope :user do 
    get '/users/current' => "registrations#show", :as => 'current_user'
    resources :users, :only => [:add, :show] 
    root :to => "registrations#show"
  end 
  

  match "powai" => "events#new"
  match "stores" => "branches#index"
  match "/contact", :to => 'pages#contact'
  match "/tnc", :to => 'pages#tnc'
  match "/privacypolicy", :to => 'pages#privacypolicy'
  match "/about", :to => 'pages#about'
  
  get "pages/privacypolicy"
  get "pages/contact"
  get "pages/tnc"
  get "pages/about"
  
  resources :branches
  match "gatewayentry" => "payments#gatewayentry" , :via => :post

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  CONV_FEE = 3.5

  include ActiveRecord::Transitions

  attr_accessor :Merchant_Id, :Order_Id, :TxnType, :actionID, :Checksum, :Redirect_Url, :workingKey, :Amount, :billing_cust_name,:billing_cust_address
  attr_accessor :billing_cust_country, :billing_cust_state,	:billing_cust_tel, :billing_cust_email, :delivery_cust_name, :delivery_cust_address
  attr_accessor :delivery_cust_state, :delivery_cust_tel, :delivery_cust_notes, :billing_cust_city, :billing_zip_code, :delivery_cust_city, :delivery_zip_code
  attr_accessor :AuthDesc
  validates :order_id, :presence => true  
  validates :amount, :presence => true
  validates :p_mode, :presence => true
  
  
  belongs_to :member
  belongs_to :user  
  validates :member_id, :presence => true
  validates :user_id, :presence => true
  validates :branch_id, :presence => true
  validates :payment_for, :presence => true
  validates :channel, :presence => true
  attr_accessor :months
  before_create :dependent_valid?
  after_save :process_state
  
  def MerchantId
    "M_jbadmin_8205"
  end
  
  def WorkingKey
    "hmuadaclfx2futatbfld06jz4p4k32ee"
  end
  
  def RedirectUrl
    #"http://192.168.1.103:3000/gatewayentry"
    "http://accounts.justbooksclc.com/gatewayentry"
  end
  
  def OrderId
    self.id
  end
  
  def get_checksum
    str = self.MerchantId + "|" + self.OrderId.to_s + "|" + self.amount.to_s + "|" + self.RedirectUrl + "|" + self.WorkingKey;
    self.Checksum = Zlib.adler32(str)
    return self.Checksum.to_s
  end
  
  def verifyChecksum(checkSum, authDesc)
    s_amount =  "%0.2f" % self.amount
    str = self.MerchantId+"|"+self.id.to_s+"|"+s_amount+"|"+authDesc+"|"+self.WorkingKey;
    curr_checksum = Zlib.adler32(str).to_s
    curr_checksum.eql?(checkSum) ? true : false
  end
  
  def calc_conv_fee
    if txn_amount.to_i < 151
      conv_fee = "%0.2f" % (txn_amount * (Payment::CONV_FEE.to_f + 2)/100)
    else
      conv_fee = "%0.2f" % (txn_amount * Payment::CONV_FEE.to_f/100)
    end
    conv_fee
  end  
  
  
  state_machine do
    state :PrePayment # first one is the initial state before sending  for payement
    state :PendingPayment # if sent to payment gateway
    state :ConfirmPayment #
    state :FailedPayment
    state :UnknownPayment
    state :Cancel
    
    event :sent do
      transitions :to => :PendingPayment, :from => [:PrePayment]
    end
    event :paid do
      transitions :to => :ConfirmPayment, :from => [:PendingPayment]
    end
    event :failed do
      transitions :to => :FailedPayment, :from => [:PendingPayment]
    end
    
    event :unknown do
      transitions :to => :UnknownPayment, :from => [:PendingPayment]
    end
    event :cancel do
      transitions :to => :Cancelled, :from => [:PrePayment]
    end
  end
  
  def processEvent(event)
    case 
      when event.eql?('sent') then sent
      when event.eql?('paid') then paid
      when event.eql?('cancel') then cancel
      when event.eql?('failed') then failed
      when event.eql?('unknown') then unknown
    end
  end
  def process_state
    case self.payment_for
          when 'Renewal' 
          case self.state
                when 'ConfirmPayment'
                    renew = Renewal.find(self.order_id)
                    renew.execute!
                    renew.send_mail
                when 'Cancelled'
                    renew = Renewal.find(self.order_id)
                    renew.cancel!
                when 'PendingPayment'
                    renew = Renewal.find(self.order_id)
                    renew.payment_id = self.id
                    renew.save!
                    renew.sent!
                    
          end
          when 'Signup' 
          case self.state
                when 'ConfirmPayment'
                    signup = Signup.find(self.order_id)
                    signup.execute!
                    signup.migrate
                when 'Cancelled'
                    signup = Signup.find(self.order_id)
                    signup.cancel!
                when 'PendingPayment'
                    signup = Signup.find(self.order_id)
                    signup.payment_id = self.id
                    signup.save!
                    signup.sent!
                    
          end
    end
  end
  
  def dependent_valid?
    case self.payment_for
      when 'Renewal' 
        renew = Renewal.find(self.order_id)
        if renew.state.eql?('New') 
          return true 
        else 
          errors.add(:payment_for, "Renewal is "+renew.state)
          return false
        end
      when 'Signup' 
        signup = Signup.find(self.order_id)
        if signup.state.eql?('New') 
          return true 
        else 
          errors.add(:payment_for, "Signup is "+signup.state)
          return false
        end
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  protect_from_forgery :only => [:create, :update, :destroy]
  before_filter :authenticate_user!,  :only => [:create, :update, :destroy, :show, :new, :index, :gatewayentry]
  
  # GET /payments
  # GET /payments.xml
  def index
    @payments = Payment.find_all_by_user_id(current_user.id).paginate(:page =>params[:page], :per_page => 9)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.xml
  def show
    @payment = Payment.find(params[:id])
    if  @payment.user_id != current_user.id  
      @payment = nil
      flash[:notice] = "Unable display. Not your payment?"
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.xml
  def new
    @payment = Payment.new
    case params[:for]
      when 'ren'
        @payment.payment_for = 'Renewal'
        renewal = Renewal.find(params[:id])
        @payment.txn_amount = renewal.amount 
        @payment.member_id = renewal.member_id
      when 'sig'
        @payment.payment_for = 'Signup'
        signup = Signup.find(params[:id])
        @payment.txn_amount = signup.paid_amt 
        @payment.member_id = signup.id
    end
    @payment.channel = "Web"
    @payment.user_id = current_user.id
    @payment.order_id =  params[:id]
    @payment.branch_id = 801 #remove hard coding
    @payment.state = "PrePayment"
    @payment.p_mode = 'Credit Card'
    @payment.fee = @payment.calc_conv_fee #15 #convinience fee
    @payment.amount = @payment.txn_amount + @payment.fee
  end

  # GET /payments/1/edit
  #def edit
  #  @payment = Payment.find(params[:id])
  #end

  # POST /payments
  # POST /payments.xml
  def create
    @payment = Payment.new(params[:payment])
    if @payment.save
      @payment.sent!
      if @payment.payment_for.eql?("Signup")
        @member = Signup.find(@payment.order_id)
      end
      render 'gateway'
    else
      render :action => "new"
    end
    
  end

  # PUT /payments/1
  # PUT /payments/1.xml
  #def update
  #  @payment = Payment.find(params[:id])

  #  respond_to do |format|
  #    if @payment.update_attributes(params[:payment])
  #      format.html { redirect_to(@payment, :notice => 'Payment was successfully updated.') }
  #      format.xml  { head :ok }
  #    else
  #      format.html { render :action => "edit" }
  #      format.xml  { render :xml => @payment.errors, :status => :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /payments/1
  # DELETE /payments/1.xml
  #def destroy
  #  @payment = Payment.find(params[:id])
  #  @payment.destroy

  #  respond_to do |format|
  #    format.html { redirect_to(payments_url) }
  #    format.xml  { head :ok }
  #  end
  #end
  
  def gatewayentry 
    order_Id = params[:Order_Id]
    merchant_Id = params[:Merchant_Id]
    redirect_Url = params[:redirect_Url]
    checksum = params[:Checksum]
    amount = params[:Amount]
    authDesc = params[:AuthDesc]
    
    @payment = Payment.find(order_Id)
    
    if @payment.verifyChecksum(checksum, authDesc) and valid_request?
      case authDesc
        when "Y"
          @payment.state = "ConfirmPayment"
          @payment.details = "Thank you. Your credit card has been charged, your order will be executed shortly."
        when "B"
          @payment.state = "UnknownPayment"
          @payment.details = "Thank you. We will keep you posted regarding the status of your order through e-mail"
        when "N"
          @payment.state = "FailedPayment" #"ConfirmPayment" use for testing
          @payment.details = "Your transaction has been declined by the merchant. Please verify your details and retry."
      end
      if (@payment.save!)
        flash[:notice] = @payment.details
      else
        flash[:notice] = @payment.details + "Failed to record the payment. Please contact customer care."
      end
    else
      reset_session
      flash[:notice] = "The transaction could not be verified."
    end
    
    redirect_to(@payment)
  end
  
  def valid_request?
    #abc=""
    request.get? ||
    form_authenticity_token == params[:Merchant_Param] ||
    form_authenticity_token == request.headers['X-CSRF-Token']
    
    #logger.debug "RENU  check here "+ abc 
    #logger.debug "fat " + form_authenticity_token
    #logger.debug "session "+ session[:_csrf_token]
    #logger.debug "params " + params[:Merchant_Param]
    #logger.debug "header" + request.headers['X-CSRF-Token']
    #xyz = !protect_against_forgery? || request.get? ||
    #form_authenticity_token == params[:Merchant_Param] ||
    #form_authenticity_token == request.headers['X-CSRF-Token'] 
    #logger.debug xyz.to_s
    
    #abc.eql?("TRUE") ? true : false
    
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
			
    <%= f.hidden_field :order_id , :value=> @payment.order_id %>
    <%= f.hidden_field :p_mode , :value=> @payment.p_mode %>
    <%= f.hidden_field :state , :value=> @payment.state %>
    <%= f.hidden_field :amount , :value=> @payment.amount %>
    <%= f.hidden_field :fee , :value=> @payment.fee %>
    <%= f.hidden_field :txn_amount , :value=> @payment.txn_amount %>
    <%= f.hidden_field :member_id , :value=> @payment.member_id %>
    <%= f.hidden_field :channel , :value=> @payment.channel %>
    <%= f.hidden_field :user_id , :value=> @payment.user_id %>
    <%= f.hidden_field :branch_id , :value=> @payment.branch_id %>
    <%= f.hidden_field :payment_for , :value=> @payment.payment_for %>
    
    <div class="heading"> Payment Details </div>
      
      Amount         : <%= @payment.txn_amount %><br/>
      Convenience fee: <%= @payment.fee %> <br/>
      <b>Total Amount : <%= @payment.amount %><br/></b>
    <br/>
    <%= f.submit "PAY NOW", :class=>"btn_link" %>
    <br/>
  </div>
<% end %>

app/views/payments/edit.html.erb
<div class="span-25">
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>
</div>

app/views/payments/gateway.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$(document).ready(function () {
    form = document.forms["paymentDetails"];
    form.submit();
	});
<% end -%>
<div class="span-25">
<%= form_tag("https://www.ccavenue.com/shopzone/cc_details.jsp", :id=>"paymentDetails", :method=>"post") do %>
  <div class="actions">
    REDIRECTING TO PAYMENT GATEWAY PLEASE DO NOT PRESS BACK BUTTON  
    <%= hidden_field_tag :Merchant_Param, form_authenticity_token %>
    <%= hidden_field_tag :Order_Id , @payment.OrderId %>
    <%= hidden_field_tag :Merchant_Id ,  @payment.MerchantId %>
    <%= hidden_field_tag :TxnType ,  "A" %>
    <%= hidden_field_tag :actionID,  "TXN" %>
    <%= hidden_field_tag :Checksum ,  @payment.get_checksum %>
    <%= hidden_field_tag :Redirect_Url ,  @payment.RedirectUrl %>
    <% if !@payment.payment_for.eql?('Signup') %>
      <%= hidden_field_tag :billing_cust_name, @payment.member.name %>
			<%= hidden_field_tag :billing_cust_address ,@payment.member.address %>
			<%= hidden_field_tag :billing_cust_country ,"INDIA" %>
			<%= hidden_field_tag :billing_cust_state , @payment.member.state %>
			<%= hidden_field_tag :billing_cust_tel ,@payment.member.mphone %>
			<%= hidden_field_tag :billing_cust_email ,@payment.user.email %>
			<%= hidden_field_tag :delivery_cust_name , @payment.user.username %>
			<%= hidden_field_tag :delivery_cust_address ,@payment.member.address %>
			<%= hidden_field_tag :delivery_cust_state ,@payment.member.state %>
			<%= hidden_field_tag :delivery_cust_tel ,@payment.member.mphone %>
			<%= hidden_field_tag :delivery_cust_notes ,"" %>
			<%= hidden_field_tag :billing_cust_city ,@payment.member.city %>
			<%= hidden_field_tag :billing_zip_code ,@payment.member.pincode %>
			<%= hidden_field_tag :delivery_cust_city ,@payment.member.city %>
			<%= hidden_field_tag :delivery_zip_code ,@payment.member.pincode %>
    <% else %>
       <%= hidden_field_tag :billing_cust_name, @member.name %>
			<%= hidden_field_tag :billing_cust_address ,@member.address %>
			<%= hidden_field_tag :billing_cust_country ,"INDIA" %>
			<%= hidden_field_tag :billing_cust_tel ,@member.mphone %>
			<%= hidden_field_tag :billing_cust_email ,@payment.user.email %>
			<%= hidden_field_tag :delivery_cust_name , @payment.user.username %>
			<%= hidden_field_tag :delivery_cust_address ,@member.address %>
			<%= hidden_field_tag :delivery_cust_tel ,@member.mphone %>
			<%= hidden_field_tag :delivery_cust_notes ,"" %>
			<%= hidden_field_tag :billing_cust_city ,"" %>
			<%= hidden_field_tag :billing_zip_code ,"" %>
			<%= hidden_field_tag :delivery_cust_city ,"" %>
			<%= hidden_field_tag :delivery_zip_code ,"" %> 
    <% end %>
      <%= hidden_field_tag :Amount ,  @payment.amount %>
      <!--%= hidden_field_tag :billing_cust_notes, "SUB-MERHCANT TEST" %-->
  </div>
  <!--%= submit_tag %-->
<% end %>
</div>

app/views/payments/index.html.erb
<div class="span-25">
<div class="span-22">
<h3>Your payments</h3>

<table>
  <tr>
    <th class="span-3">Payment for</th>
    <th class="span-3">Done at </th>
    <th class="span-3">Status</th>
    <th class="span-3">Total Amount</th>
  </tr>
<%= will_paginate(@payments) %>
<% @payments.each do |payment| %>
  <tr>
    <td class="span-3"><%= payment.payment_for %></td>
    <td class="span-3"><%=payment.created_at.strftime('%d-%b-%Y') %></td>
    <td class="span-3"><%= payment.state %> </td>
    <td class="span-3"><%= payment.amount %></h3></td>
    <td><%= link_to 'Show', payment %></td>
    <!--td><%= link_to 'Cancel', edit_payment_path(payment) %></td-->
  </tr>
<% end %>
</table>

<br />
</div>
</div>

app/views/payments/new.html.erb
# google analytics tracking code starts
  <%= javascript_tag :defer => 'defer' do -%>
    <script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-24987175-1']);
		  _gaq.push(['_setDomainName', '.justbooksclc.com']);
		  _gaq.push(['_trackPageview']);
		
		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		
		</script>
  <% end %>
# google analytics tracking code ends

<div class="span-25">
<div class="input_box">  
<div class="breadcrumb"> INVOICE </div>

  <div class="inner_box">  
    <%= render 'form' %>

    <%= link_to 'Back', :back %>
  
  </div>
</div>
</div>

app/views/payments/show.html.erb
# google analytics tracking code starts
  <%= javascript_tag :defer => 'defer' do -%>
    <script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-24987175-1']);
		  _gaq.push(['_setDomainName', '.justbooksclc.com']);
		  _gaq.push(['_trackPageview']);
		
		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		
		</script>
  <% end %>
# google analytics tracking code ends

<div class="span-25">
<div class="span-14">
<p id="notice"><%= notice %></p>
  <% unless @payment.nil? %>
  <%= field_set_tag 'Payment Details' do %>
      Payment for    :<%= @payment.payment_for %> <br/>  
      Status         :<%= @payment.state %>         <br/>
      Details        :<%=@payment.details %></br>
      Amount         : <%= @payment.txn_amount %><br/>
      Convinience fee:<%= @payment.fee %> <br/>
      <h3>Total Amount :<%= @payment.amount %><br/></h3>
      done at <%=@payment.created_at.strftime('%d-%b-%Y') %></br>
  <% end %>
  <% end %>

<%= link_to 'settings', current_user_path %> |
<%= link_to 'home', root_path %>
</div>
</div>