config/routes.rb
WebstoreApp::Application.routes.draw do

  resources :events

  resources :signups

  resources :renewals

  resources :payments 
  
  resources :plans
      

  
  devise_for :users, :controllers => {:registrations => 'registrations'} 
  devise_scope :user do 
    get '/users/current' => "registrations#show", :as => 'current_user'
    resources :users, :only => [:add, :show] 
    root :to => "registrations#show"
  end 
  

  match "powai" => "events#new"
  match "stores" => "branches#index"
  match "/contact", :to => 'pages#contact'
  match "/tnc", :to => 'pages#tnc'
  match "/privacypolicy", :to => 'pages#privacypolicy'
  match "/about", :to => 'pages#about'
  
  get "pages/privacypolicy"
  get "pages/contact"
  get "pages/tnc"
  get "pages/about"
  
  resources :branches
  match "gatewayentry" => "payments#gatewayentry" , :via => :post

end

app/views/layouts/_flash.html.erb
<%= flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}", :class => "#{name}" %>
  <% if defined?(flush_flash) and flush_flash == true %>
		<% flash.clear %>
	<% end %>
<% end -%>

app/views/layouts/_main_nav.html.erb
	<div class="span-25">
		<div class="span-14 right">
    <% if user_signed_in? %>
      <div class="toplinkText span-3"> Hi <%= current_user.username %></div>
      <div class="toplink span-3"> <%= link_to "SETTING", current_user_path %></div>
      <div class="toplink span-3"> <%= link_to "LOGOUT", destroy_user_session_path %></div>
    <% else %>
      <div class="toplink span-3">      <%= link_to "SIGN IN", new_user_session_path %></div>
    <% end %>
    </div>
    <p class="masthead"><%= image_tag('JBK.jpg', :id => 'logo')%></p>
    	

  </div>
  <div class="span-24 prepend-2" style="position:absolute; top:58px">
      <div id="mainNav" >
            <ul>
            	<li class="mainNav"><%= link_to "YOUR ACCOUNT", current_user_path %></li>
            	<li class="mainNavSeperator01"><spacer type="block" width="3"></spacer></li>
              <!-- <li class="mainNav"><%#= link_to "PLANS", stores_path %></li> -->
            	<li class="mainNavSeperator01"><spacer type="block" width="3"></spacer></li>
            </ul>
            <!-- nav ends -->
      	</div>
        <!-- main navigation ends -->
      <div class="right">
        
      </div>
    
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag 'screen.css', :media => 'screen,projection' %>
  <%= stylesheet_link_tag 'print.css', :media => 'print' %>

  <!--[if lt IE 8]><stylesheet_link_tag 'ie.css' media='screen, projection'><![endif]-->

  <%= stylesheet_link_tag 'plugins/fancy-type/screen.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'application.css', :media => 'screen,projection' %>
	<%= stylesheet_link_tag 'jquery.jscrollpane.css', :media => 'screen,projection' %>
  
	<%= stylesheet_link_tag 'http://cdn.webrupee.com/font', :media=>'screen,projection' %>

  <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jit' %>
  <%= javascript_include_tag 'jquery-1.5.2.min.js'%>
  <%= javascript_include_tag 'jquery-ui-1.8.11.custom.min.js'%>
	<%= javascript_include_tag 'jquery.jscrollpane.min.js'%>
	<%= javascript_include_tag 'jquery.printElement.min.js'%>
  <%= javascript_include_tag "booklet/jquery.easing.1.3.js" %>
  <%= javascript_include_tag "booklet/jquery.booklet.1.2.0.min.js" %>
  <%= stylesheet_link_tag "jquery.booklet.1.2.0.css", :media=>"screen, projection, tv" %>
  
  <%= csrf_meta_tag %>

	<script type="text/javascript">
	    $(document).ready(function() {
					$('.scroll-pane').jScrollPane();
	        <%= yield :javascript %>
	    });
	</script>
	
</head>

<body>

<div class="container  background">	
  <%= render :partial => "layouts/main_nav" %>
	<div class="span-25 prepend-2" style="height:506px;">
        <div class="span-18 breadcrumbs">
          <%= breadcrumbs.render(:format => :inline, :separator => '>') %>
        </div>
  			<section class="span-18 round">
				<% flash.each do |key, value| %>
					<div class="flash <%= key %>"><%= value %></div>
				<% end %>
        </section>
        <br/>
    <%= yield %>
	</div>

	<div class="span-25 footer quiet">
		<span class="span-8 prepend-1"><p id="footer">Copyright © 2011 JustBooks, All rights reserved. </p></span>
    <span class="span-3"><%= link_to "Contact Us", contact_path %> </span>
    <span class="span-5"><%= link_to "Stores", stores_path %> (<a href="http://justbooksclc.com/StoreLocations.action" target="_blank"> Locations </a>) </span>
    <span class="span-3"><%= link_to "About Us", about_path %></span>
    <span class="span-3"><%= link_to "Privacy Policy", privacypolicy_path %> </span>
    <span class="span-3"><%= link_to "Terms of Use", tnc_path %></span>
	</div>

</div>

</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag 'screen.css', :media => 'screen,projection' %>
  <%= stylesheet_link_tag 'print.css', :media => 'print' %>

  <!--[if lt IE 8]><stylesheet_link_tag 'ie.css' media='screen, projection'><![endif]-->

  <%= stylesheet_link_tag 'plugins/fancy-type/screen.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'application.css', :media => 'screen,projection' %>
	<%= stylesheet_link_tag 'jquery.jscrollpane.css', :media => 'screen,projection' %>
  
	<%= stylesheet_link_tag 'http://cdn.webrupee.com/font', :media=>'screen,projection' %>

  <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jit' %>
  <%= javascript_include_tag 'jquery-1.5.2.min.js'%>
  <%= javascript_include_tag 'jquery-ui-1.8.11.custom.min.js'%>
	<%= javascript_include_tag 'jquery.jscrollpane.min.js'%>
	<%= javascript_include_tag 'jquery.printElement.min.js'%>
  <%= javascript_include_tag "booklet/jquery.easing.1.3.js" %>
  <%= javascript_include_tag "booklet/jquery.booklet.1.2.0.min.js" %>
  <%= stylesheet_link_tag "jquery.booklet.1.2.0.css", :media=>"screen, projection, tv" %>
  
  <%= csrf_meta_tag %>


	<script type="text/javascript">
	    $(document).ready(function() {
	        <%= yield :javascript %>
	    });
	</script>
	
</head>

<body>

	
	<div class="span-24">
		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/corp.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag 'screen.css', :media => 'screen,projection' %>
  <%= stylesheet_link_tag 'print.css', :media => 'print' %>

  <!--[if lt IE 8]><stylesheet_link_tag 'ie.css' media='screen, projection'><![endif]-->

  <%= stylesheet_link_tag 'plugins/fancy-type/screen.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'application.css', :media => 'screen,projection' %>
	<%= stylesheet_link_tag 'jquery.jscrollpane.css', :media => 'screen,projection' %>
  
	<%= stylesheet_link_tag 'http://cdn.webrupee.com/font', :media=>'screen,projection' %>

  <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jit' %>
  <%= javascript_include_tag 'jquery-1.5.2.min.js'%>
  <%= javascript_include_tag 'jquery-ui-1.8.11.custom.min.js'%>
	<%= javascript_include_tag 'jquery.jscrollpane.min.js'%>
	<%= javascript_include_tag 'jquery.printElement.min.js'%>
  <%= javascript_include_tag "booklet/jquery.easing.1.3.js" %>
  <%= javascript_include_tag "booklet/jquery.booklet.1.2.0.min.js" %>
  <%= stylesheet_link_tag "jquery.booklet.1.2.0.css", :media=>"screen, projection, tv" %>
  
  <%= csrf_meta_tag %>

	<script type="text/javascript">
	    $(document).ready(function() {
					$('.scroll-pane').jScrollPane();
	        <%= yield :javascript %>
	    });
	</script>
	
</head>

<body>

<div class="container  background">	
	<% if user_signed_in? and current_user.isKid? %>
    <%= render :partial => "layouts/kids_nav" %>
  <% else %>
      <%= render :partial => "layouts/main_nav" %>
  <% end %>
	<div class="span-25 prepend-2" >
        <div class="span-18 breadcrumbs">
          <%= breadcrumbs.render(:format => :inline, :separator => '>') %>
        </div>
  			<section class="span-18 round">
				<% flash.each do |key, value| %>
					<div class="flash <%= key %>"><%= value %></div>
				<% end %>
        </section>
        <br/>
    <%= yield %>
	</div>

	<div class="span-25 footer quiet">
		<span class="span-8 prepend-1"><p id="footer">Copyright © 2011 JustBooks, All rights reserved. </p></span>
    <span class="span-3"><%= link_to "Contact Us", contact_path %> </span>
    <span class="span-5"><%= link_to "Stores", stores_path %> (<a href="http://justbooksclc.com/StoreLocations.action" target="_blank"> Locations </a>) </span>
    <span class="span-3"><%= link_to "About Us", about_path %></span>
    <span class="span-3"><%= link_to "Privacy Policy", privacypolicy_path %> </span>
    <span class="span-3"><%= link_to "Terms of Use", tnc_path %></span>
	</div>


</div>

</body>
</html>